# Generated by Django 2.2.6 on 2019-10-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NestedCategory',
            fields=[
                ('category_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.IntegerField(null=True)),
                ('lft', models.IntegerField()),
                ('rgt', models.IntegerField()),
            ],
        ),
    ]
