# Generated by Django 2.2.6 on 2019-10-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nestedcategory',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
