# Generated by Django 2.2.6 on 2019-10-30 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0002_auto_20191030_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nestedcategory',
            name='parent',
        ),
    ]
